
const K="isa_app_data_v04",K3="isa_app_data_v03";
function dk(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function pd(s){if(!s)return null;let[a,b,c]=s.split("-").map(Number);return new Date(a,b-1,c,12)}
function blank(){return{version:4,habits:[],habitCompletions:{},prayers:[],prayerCompletions:{},tasks:[],taskCompletions:{}}}
function load(){let r=localStorage.getItem(K);if(r)try{return JSON.parse(r)}catch{};let s=blank(),old=localStorage.getItem(K3);if(old)try{let o=JSON.parse(old);s={...s,...o,version:4};s.tasks=(s.tasks||[]).map(t=>({...t,notes:t.notes||"",category:t.category||"Pessoal",priority:t.priority||"normal",time:t.time||"",frequency:t.frequency||{type:"date",date:dk()}}))}catch{};localStorage.setItem(K,JSON.stringify(s));return s}
let S=load(),habitView="today",prayerView="today",taskView="today",activeHabit=null,activePrayer=null,activeTask=null;
function save(){localStorage.setItem(K,JSON.stringify(S));renderAll()}
function key(id,date=dk()){return `${id}|${date}`}
function done(map,id,date=dk()){return !!map[key(id,date)]}
function toggle(map,id){let k=key(id);map[k]?delete map[k]:map[k]=true;save()}
function sched(item,date){if(item.archived)return false;let f=item.frequency||{type:"daily"},x=dk(date);if(f.type==="daily")return true;if(f.type==="weekly")return(f.weekdays||[]).includes(date.getDay());if(f.type==="monthly")return date.getDate()===Number(f.day||1);if(f.type==="yearly"){let d=pd(f.date);return d&&d.getDate()===date.getDate()&&d.getMonth()===date.getMonth()}if(f.type==="date")return f.date===x;if(f.type==="range")return f.start&&f.end&&x>=f.start&&x<=f.end;return true}
function todayHabits(){return S.habits.filter(x=>sched(x,new Date()))}
function todayPrayers(){return S.prayers.filter(x=>sched(x,new Date()))}
function todayTasks(){return S.tasks.filter(x=>sched(x,new Date()))}
function fdate(){return new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).format(new Date())}
todayText.textContent=fdate();agendaDate.textContent=fdate();
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function short(s){let d=pd(s);return d?new Intl.DateTimeFormat("pt-BR").format(d):""}
function flabel(i){let f=i.frequency||{type:"daily"};if(f.type==="daily")return"Todos os dias";if(f.type==="weekly"){let n=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];return(f.weekdays||[]).map(x=>n[x]).join(", ")}if(f.type==="monthly")return`Todo dia ${f.day}`;if(f.type==="yearly"){let d=pd(f.date);return d?`Todo ${String(d.getDate()).padStart(2,"0")}/${String(d.getMonth()+1).padStart(2,"0")}`:"Anual"}if(f.type==="date")return`Em ${short(f.date)}`;if(f.type==="range")return`${short(f.start)} a ${short(f.end)}`;return""}

function renderHabits(){let a=habitView==="today"?todayHabits():S.habits.filter(x=>!x.archived),r=habitList;r.innerHTML="";habitEmpty.classList.toggle("hidden",a.length>0);a.forEach(h=>{let z=done(S.habitCompletions,h.id),e=document.createElement("article");e.className="item-card"+(z?" done":"");e.innerHTML=`<div class="item-top"><span class="item-icon">${h.icon||"⭐"}</span>${h.time?`<span class="item-time">${h.time}</span>`:""}</div><div><button class="item-title" data-hd="${h.id}">${esc(h.name)}</button><div class="item-category">${esc(h.category||"")}</div></div>${habitView==="today"?`<button class="check ${z?"done":""}" data-h="${h.id}">${z?"✓":""}</button>`:""}`;r.appendChild(e)});r.querySelectorAll("[data-h]").forEach(b=>b.onclick=()=>toggle(S.habitCompletions,b.dataset.h));r.querySelectorAll("[data-hd]").forEach(b=>b.onclick=()=>openHabit(b.dataset.hd))}
function renderPrayers(){let a=prayerView==="today"?todayPrayers():S.prayers.filter(x=>!x.archived),r=prayerList;r.innerHTML="";if(!a.length){r.innerHTML='<p class="empty">Nenhuma oração nesta seção.</p>';return}a.forEach(p=>{let z=done(S.prayerCompletions,p.id),e=document.createElement("article");e.className="list-item"+(z?" done":"");e.innerHTML=`<div class="list-main"><strong>${esc(p.name)}</strong><small>${esc(flabel(p))}${p.time?` • ${p.time}`:""}${z?" • Finalizada hoje":""}</small></div><button class="status" data-p="${p.id}">${z?"✓":"Abrir"}</button>`;r.appendChild(e)});r.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>openPrayer(b.dataset.p))}
function renderTasks(){let a=taskView==="today"?todayTasks():S.tasks.filter(x=>!x.archived),r=taskList;r.innerHTML="";if(!a.length){r.innerHTML='<p class="empty">Nenhuma tarefa nesta seção.</p>';return}a.forEach(t=>{let z=done(S.taskCompletions,t.id),e=document.createElement("article");e.className=`list-item ${z?"done ":""}${t.priority==="high"?"priority-high":t.priority==="low"?"priority-low":""}`;e.innerHTML=`<div class="list-main"><strong data-td="${t.id}">${esc(t.name)}</strong><small>${esc(t.category||"")} • ${esc(flabel(t))}${t.time?` • ${t.time}`:""}${z?" • Concluída":""}</small></div>${taskView==="today"?`<button class="status" data-t="${t.id}">${z?"✓":"Concluir"}</button>`:""}`;r.appendChild(e)});r.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>toggle(S.taskCompletions,b.dataset.t));r.querySelectorAll("[data-td]").forEach(b=>b.onclick=()=>openTask(b.dataset.td))}
function renderStats(){let h=todayHabits(),p=todayPrayers(),t=todayTasks(),hc=h.filter(x=>done(S.habitCompletions,x.id)).length,pc=p.filter(x=>done(S.prayerCompletions,x.id)).length,tc=t.filter(x=>done(S.taskCompletions,x.id)).length,total=h.length+p.length+t.length,n=hc+pc+tc,pct=total?Math.round(n/total*100):0;habitSummary.textContent=`${hc} de ${h.length}`;prayerSummary.textContent=`${pc} de ${p.length}`;taskSummary.textContent=`${t.length-tc} pendentes`;statHabits.textContent=`${hc}/${h.length}`;statPrayers.textContent=`${pc}/${p.length}`;statTasks.textContent=`${tc}/${t.length}`;overallPercent.textContent=`${pct}%`;overallBar.style.width=`${pct}%`;let q=[...h.filter(x=>!done(S.habitCompletions,x.id)).map(x=>`Hábito: ${x.name}`),...p.filter(x=>!done(S.prayerCompletions,x.id)).map(x=>`Oração: ${x.name}`),...t.filter(x=>!done(S.taskCompletions,x.id)).map(x=>`Tarefa: ${x.name}`)];pendingList.innerHTML=q.length?q.slice(0,8).map(x=>`<li>${esc(x)}</li>`).join(""):"<li>Nenhuma pendência 🎉</li>"}
function renderAll(){renderHabits();renderPrayers();renderTasks();renderStats()}

document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>go(b.dataset.target));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));function go(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.target===id));scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-habit-view]").forEach(b=>b.onclick=()=>{habitView=b.dataset.habitView;document.querySelectorAll("[data-habit-view]").forEach(x=>x.classList.toggle("active",x===b));renderHabits()});
document.querySelectorAll("[data-prayer-view]").forEach(b=>b.onclick=()=>{prayerView=b.dataset.prayerView;document.querySelectorAll("[data-prayer-view]").forEach(x=>x.classList.toggle("active",x===b));renderPrayers()});
document.querySelectorAll("[data-task-view]").forEach(b=>b.onclick=()=>{taskView=b.dataset.taskView;document.querySelectorAll("[data-task-view]").forEach(x=>x.classList.toggle("active",x===b));renderTasks()});

createBtn.onclick=()=>createDialog.showModal();document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{if(createDialog.open)createDialog.close();if(b.dataset.action==="task")openTaskForm();else if(b.dataset.action==="habit")openHabitForm();else openPrayerForm()});

function freqUI(prefix){let t=document.getElementById(prefix+"Frequency").value,map={weekly:"Weekly",monthly:"Monthly",yearly:"Yearly",date:"DateBox",range:"Range"};["Weekly","Monthly","Yearly","DateBox","Range"].forEach(x=>document.getElementById(prefix+x).classList.add("hidden"));if(map[t])document.getElementById(prefix+map[t]).classList.remove("hidden")}
habitFrequency.onchange=()=>freqUI("habit");prayerFrequency.onchange=()=>freqUI("prayer");taskFrequency.onchange=()=>freqUI("task");
function readFreq(prefix){let t=document.getElementById(prefix+"Frequency").value,f={type:t};if(t==="weekly"){f.weekdays=[...document.querySelectorAll(`#${prefix}Weekly input:checked`)].map(x=>Number(x.value));if(!f.weekdays.length)throw"Escolha pelo menos um dia."}if(t==="monthly")f.day=Number(document.getElementById(prefix+"MonthDay").value);if(t==="yearly")f.date=document.getElementById(prefix+"YearDate").value;if(t==="date")f.date=document.getElementById(prefix+"Date").value;if(t==="range"){f.start=document.getElementById(prefix+"StartDate").value;f.end=document.getElementById(prefix+"EndDate").value;if(!f.start||!f.end||f.end<f.start)throw"Confira o intervalo."}if((t==="yearly"||t==="date")&&!f.date)throw"Escolha a data.";return f}
function fillFreq(prefix,f={type:"daily"}){document.getElementById(prefix+"Frequency").value=f.type||"daily";document.querySelectorAll(`#${prefix}Weekly input`).forEach(c=>c.checked=(f.weekdays||[]).includes(Number(c.value)));document.getElementById(prefix+"MonthDay").value=f.day||1;document.getElementById(prefix+"YearDate").value=f.date||"";document.getElementById(prefix+"Date").value=f.date||"";document.getElementById(prefix+"StartDate").value=f.start||"";document.getElementById(prefix+"EndDate").value=f.end||"";freqUI(prefix)}

function openTaskForm(t=null){taskFormTitle.textContent=t?"Editar tarefa":"Nova tarefa";taskId.value=t?.id||"";taskName.value=t?.name||"";taskNotes.value=t?.notes||"";taskCategory.value=t?.category||"Pessoal";taskPriority.value=t?.priority||"normal";taskTime.value=t?.time||"";fillFreq("task",t?.frequency||{type:"date",date:dk()});taskFormDialog.showModal()}
cancelTaskForm.onclick=()=>taskFormDialog.close();taskForm.onsubmit=e=>{e.preventDefault();try{let id=taskId.value,o={id:id||crypto.randomUUID(),name:taskName.value.trim(),notes:taskNotes.value.trim(),category:taskCategory.value,priority:taskPriority.value,time:taskTime.value,frequency:readFreq("task"),archived:false};if(id)S.tasks[S.tasks.findIndex(x=>x.id===id)]={...S.tasks.find(x=>x.id===id),...o};else S.tasks.push(o);save();taskFormDialog.close()}catch(m){alert(m)}}
function openTask(id){activeTask=id;let t=S.tasks.find(x=>x.id===id);taskDetailName.textContent=t.name;taskDetailMeta.textContent=[t.category,({high:"Alta",normal:"Normal",low:"Baixa"})[t.priority],flabel(t),t.time].filter(Boolean).join(" • ");taskDetailNotes.textContent=t.notes||"Sem descrição.";taskDetailDialog.showModal()}
editTask.onclick=()=>{let t=S.tasks.find(x=>x.id===activeTask);taskDetailDialog.close();openTaskForm(t)};archiveTask.onclick=()=>{let t=S.tasks.find(x=>x.id===activeTask);if(confirm(`Arquivar "${t.name}"?`)){t.archived=true;save();taskDetailDialog.close()}};taskItemHistory.onclick=()=>showItemHistory("task",activeTask);closeTaskDetail.onclick=()=>taskDetailDialog.close();

function openHabitForm(h=null){habitFormTitle.textContent=h?"Editar hábito":"Novo hábito";habitId.value=h?.id||"";habitName.value=h?.name||"";habitIcon.value=h?.icon||"📖";habitCategory.value=h?.category||"Espiritual";habitTime.value=h?.time||"";fillFreq("habit",h?.frequency);habitDialog.showModal()}
cancelHabit.onclick=()=>habitDialog.close();habitForm.onsubmit=e=>{e.preventDefault();try{let id=habitId.value,o={id:id||crypto.randomUUID(),name:habitName.value.trim(),icon:habitIcon.value,category:habitCategory.value,time:habitTime.value,frequency:readFreq("habit"),archived:false};if(id)S.habits[S.habits.findIndex(x=>x.id===id)]={...S.habits.find(x=>x.id===id),...o};else S.habits.push(o);save();habitDialog.close()}catch(m){alert(m)}}
function openPrayerForm(p=null){prayerFormTitle.textContent=p?"Editar oração":"Nova oração";prayerId.value=p?.id||"";prayerName.value=p?.name||"";prayerBody.value=p?.text||"";prayerTime.value=p?.time||"";fillFreq("prayer",p?.frequency);prayerFormDialog.showModal()}
cancelPrayerForm.onclick=()=>prayerFormDialog.close();prayerForm.onsubmit=e=>{e.preventDefault();try{let id=prayerId.value,o={id:id||crypto.randomUUID(),name:prayerName.value.trim(),text:prayerBody.value,time:prayerTime.value,frequency:readFreq("prayer"),archived:false};if(id)S.prayers[S.prayers.findIndex(x=>x.id===id)]={...S.prayers.find(x=>x.id===id),...o};else S.prayers.push(o);save();prayerFormDialog.close()}catch(m){alert(m)}}

function openHabit(id){activeHabit=id;let h=S.habits.find(x=>x.id===id);habitDetailIcon.textContent=h.icon||"⭐";habitDetailName.textContent=h.name;habitDetailMeta.textContent=[h.category,flabel(h),h.time].filter(Boolean).join(" • ");habitDetailDialog.showModal()}
editHabit.onclick=()=>{let h=S.habits.find(x=>x.id===activeHabit);habitDetailDialog.close();openHabitForm(h)};archiveHabit.onclick=()=>{let h=S.habits.find(x=>x.id===activeHabit);if(confirm(`Arquivar "${h.name}"?`)){h.archived=true;save();habitDetailDialog.close()}};habitItemHistory.onclick=()=>showItemHistory("habit",activeHabit);closeHabitDetail.onclick=()=>habitDetailDialog.close();
function openPrayer(id){activePrayer=id;let p=S.prayers.find(x=>x.id===id);prayerTitle.textContent=p.name;prayerMeta.textContent=[flabel(p),p.time].filter(Boolean).join(" • ");prayerText.textContent=p.text||"Sem texto cadastrado.";finishPrayer.textContent=done(S.prayerCompletions,id)?"Desmarcar finalização":"Marcar como finalizada";prayerDetailDialog.showModal()}
finishPrayer.onclick=()=>{toggle(S.prayerCompletions,activePrayer);prayerDetailDialog.close()};editPrayer.onclick=()=>{let p=S.prayers.find(x=>x.id===activePrayer);prayerDetailDialog.close();openPrayerForm(p)};archivePrayer.onclick=()=>{let p=S.prayers.find(x=>x.id===activePrayer);if(confirm(`Arquivar "${p.name}"?`)){p.archived=true;save();prayerDetailDialog.close()}};prayerItemHistory.onclick=()=>showItemHistory("prayer",activePrayer);closePrayer.onclick=()=>prayerDetailDialog.close();

function historyRows(type,id=null){let map=type==="habit"?S.habitCompletions:type==="prayer"?S.prayerCompletions:S.taskCompletions,items=type==="habit"?S.habits:type==="prayer"?S.prayers:S.tasks,rows=[];for(let k in map){let [iid,date]=k.split("|");if(id&&iid!==id)continue;let item=items.find(x=>x.id===iid);if(item)rows.push({date,name:item.name})}return rows.sort((a,b)=>b.date.localeCompare(a.date))}
function showItemHistory(type,id){historyTitle.textContent=type==="habit"?"Histórico do hábito":type==="prayer"?"Histórico da oração":"Histórico da tarefa";let rows=historyRows(type,id);historyContent.innerHTML=rows.length?rows.map(r=>`<div class="history-row done"><span>${esc(r.name)}</span><strong>${short(r.date)}</strong></div>`).join(""):'<p class="empty">Ainda não há registros.</p>';historyDialog.showModal()}
habitHistoryBtn.onclick=()=>{historyTitle.textContent="Histórico de hábitos";let r=historyRows("habit");historyContent.innerHTML=r.length?r.map(x=>`<div class="history-row done"><span>${esc(x.name)}</span><strong>${short(x.date)}</strong></div>`).join(""):'<p class="empty">Ainda não há registros.</p>';historyDialog.showModal()}
prayerHistoryBtn.onclick=()=>{historyTitle.textContent="Histórico de orações";let r=historyRows("prayer");historyContent.innerHTML=r.length?r.map(x=>`<div class="history-row done"><span>${esc(x.name)}</span><strong>${short(x.date)}</strong></div>`).join(""):'<p class="empty">Ainda não há registros.</p>';historyDialog.showModal()}
taskHistoryBtn.onclick=()=>{historyTitle.textContent="Histórico de tarefas";let r=historyRows("task");historyContent.innerHTML=r.length?r.map(x=>`<div class="history-row done"><span>${esc(x.name)}</span><strong>${short(x.date)}</strong></div>`).join(""):'<p class="empty">Ainda não há registros.</p>';historyDialog.showModal()}
closeHistory.onclick=()=>historyDialog.close();

function showArchived(type){let a=(type==="habit"?S.habits:type==="prayer"?S.prayers:S.tasks).filter(x=>x.archived);archiveTitle.textContent=type==="habit"?"Hábitos arquivados":type==="prayer"?"Orações arquivadas":"Tarefas arquivadas";archiveContent.innerHTML=a.length?a.map(x=>`<div class="list-item"><div class="list-main"><strong>${esc(x.name)}</strong></div><div class="archive-actions"><button data-restore="${x.id}" data-type="${type}">Restaurar</button></div></div>`).join(""):'<p class="empty">Nenhum item arquivado.</p>';archiveContent.querySelectorAll("[data-restore]").forEach(b=>b.onclick=()=>{let arr=b.dataset.type==="habit"?S.habits:b.dataset.type==="prayer"?S.prayers:S.tasks,item=arr.find(x=>x.id===b.dataset.restore);item.archived=false;save();showArchived(b.dataset.type)});archiveDialog.showModal()}
habitArchivedBtn.onclick=()=>showArchived("habit");prayerArchivedBtn.onclick=()=>showArchived("prayer");taskArchivedBtn.onclick=()=>showArchived("task");closeArchive.onclick=()=>archiveDialog.close();

if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
renderAll();
