const K="isa_app_data_v06",K5="isa_app_data_v05";
function dk(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function pd(s){if(!s)return null;let[a,b,c]=s.split("-").map(Number);return new Date(a,b-1,c,12)}
function blank(){return{version:6,habits:[],habitCompletions:{},prayers:[],prayerCompletions:{},tasks:[],taskCompletions:{},routine:[]}}
function load(){let r=localStorage.getItem(K);if(r)try{return JSON.parse(r)}catch{};let s=blank(),old=localStorage.getItem(K5);if(old)try{let o=JSON.parse(old);s={...s,...o,version:6,routine:o.routine||[]}}catch{};localStorage.setItem(K,JSON.stringify(s));return s}
let S=load(),habitView="today",prayerView="today",taskView="today",routineFilter="today",activeHabit=null,activePrayer=null,calendarDate=new Date(),selectedDate=new Date();
function save(){localStorage.setItem(K,JSON.stringify(S));renderAll()}
function key(id,date=dk()){return `${id}|${date}`} function done(map,id,date=dk()){return !!map[key(id,date)]}
function toggle(map,id,date=dk()){let k=key(id,date);map[k]?delete map[k]:map[k]=true;save()}
function sched(item,date){if(item.archived)return false;let f=item.frequency||{type:"daily"},x=dk(date);if(f.type==="daily")return true;if(f.type==="weekly")return(f.weekdays||[]).includes(date.getDay());if(f.type==="monthly")return date.getDate()===Number(f.day||1);if(f.type==="yearly"){let d=pd(f.date);return d&&d.getDate()===date.getDate()&&d.getMonth()===date.getMonth()}if(f.type==="date")return f.date===x;if(f.type==="range")return f.start&&f.end&&x>=f.start&&x<=f.end;return true}
function routineOn(r,date){return !r.archived&&(r.weekdays||[]).includes(date.getDay())}
const todayHabits=()=>S.habits.filter(x=>sched(x,new Date()));const todayPrayers=()=>S.prayers.filter(x=>sched(x,new Date()));const todayTasks=()=>S.tasks.filter(x=>sched(x,new Date()));
function fdate(d=new Date()){return new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).format(d)}
todayText.textContent=fdate();agendaDate.textContent=fdate();
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function short(s){let d=pd(s);return d?new Intl.DateTimeFormat("pt-BR").format(d):""}
function flabel(i){let f=i.frequency||{type:"daily"};if(f.type==="daily")return"Todos os dias";if(f.type==="weekly"){let n=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];return(f.weekdays||[]).map(x=>n[x]).join(", ")}if(f.type==="monthly")return`Todo dia ${f.day}`;if(f.type==="yearly"){let d=pd(f.date);return d?`Todo ${String(d.getDate()).padStart(2,"0")}/${String(d.getMonth()+1).padStart(2,"0")}`:"Anual"}if(f.type==="date")return`Em ${short(f.date)}`;if(f.type==="range")return`${short(f.start)} a ${short(f.end)}`;return""}
const EMOJIS=["📖","📚","📕","📘","📙","📗","📝","✏️","🧠","🎓","💡","✅","⭐","🌟","✨","🌞","🌙","☀️","☁️","🌈","🌸","🌷","🌹","🌻","🌿","🍃","🌱","🍎","🍓","🍌","🥗","🥣","🍵","☕","💧","🥤","🧴","🪥","🛁","🚿","🧼","🧹","🧺","🏠","🛏️","🪴","🕯️","🙏","✝️","⛪","📿","🕊️","❤️","💗","💖","💛","💚","💙","💜","😊","😇","🥰","😌","😴","🤗","💪","🏃","🚶","🧘","🏋️","🤸","🚴","🏊","⚽","🏐","🎾","🎯","🎵","🎶","🎸","🎹","🎨","🎬","📷","📱","💻","⌚","⏰","📅","🗓️","⏳","💼","💰","🛍️","🧳","🚗","🚌","🚲","✈️","🐶","🐱","🦋","🐝","🍀","🌍","🔥","💤","🎁","🎂","🍽️","🧁","🍫","🥛","🧃","💊"];
emojiPicker.innerHTML=EMOJIS.map(e=>`<button type="button" class="emoji-option" data-emoji="${e}">${e}</button>`).join("");emojiPicker.querySelectorAll("[data-emoji]").forEach(b=>b.onclick=()=>selectEmoji(b.dataset.emoji));function selectEmoji(e){habitIcon.value=e;habitIconPreview.textContent=e;emojiPicker.querySelectorAll(".emoji-option").forEach(b=>b.classList.toggle("selected",b.dataset.emoji===e))}

function renderHabits(){let a=habitView==="today"?todayHabits():S.habits.filter(x=>!x.archived),r=habitList;r.innerHTML="";habitEmpty.classList.toggle("hidden",a.length>0);a.forEach(h=>{let z=done(S.habitCompletions,h.id),e=document.createElement("article");e.className="item-card"+(z?" done":"");e.innerHTML=`<div class="item-top"><span class="item-icon">${h.icon||"⭐"}</span>${h.time?`<span class="item-time">${h.time}</span>`:""}</div><div><button class="item-title" data-hd="${h.id}">${esc(h.name)}</button><div class="item-category">${esc(h.category||"")}</div></div>${habitView==="today"?`<button class="check ${z?"done":""}" data-h="${h.id}">${z?"✓":""}</button>`:""}`;r.appendChild(e)});r.querySelectorAll("[data-h]").forEach(b=>b.onclick=()=>toggle(S.habitCompletions,b.dataset.h));r.querySelectorAll("[data-hd]").forEach(b=>b.onclick=()=>openHabit(b.dataset.hd))}
function renderPrayers(){let a=prayerView==="today"?todayPrayers():S.prayers.filter(x=>!x.archived),r=prayerList;r.innerHTML="";if(!a.length){r.innerHTML='<p class="empty">Nenhuma oração nesta seção.</p>';return}a.forEach(p=>{let z=done(S.prayerCompletions,p.id),e=document.createElement("article");e.className="list-item"+(z?" done":"");e.innerHTML=`<div class="list-main"><strong>${esc(p.name)}</strong><small>${esc(flabel(p))}${p.time?` • ${p.time}`:""}${z?" • Finalizada hoje":""}</small></div><button class="status" data-p="${p.id}">${z?"✓":"Abrir"}</button>`;r.appendChild(e)});r.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>openPrayer(b.dataset.p))}
function tasksFor(date){return S.tasks.filter(x=>sched(x,date))}
function renderTasks(){let a=taskView==="today"?tasksFor(selectedDate):S.tasks.filter(x=>!x.archived),r=taskList;r.innerHTML="";if(!a.length){r.innerHTML='<p class="empty">Nenhuma tarefa nesta seção.</p>';return}a.forEach(t=>{let z=done(S.taskCompletions,t.id,dk(selectedDate)),e=document.createElement("article");e.className=`list-item ${z?"done ":""}${t.priority==="high"?"priority-high":t.priority==="low"?"priority-low":""}`;e.innerHTML=`<div class="list-main"><strong>${esc(t.name)}</strong><small>${esc(t.category||"")} • ${esc(flabel(t))}${t.time?` • ${t.time}`:""}</small></div>${taskView==="today"?`<button class="status" data-t="${t.id}">${z?"✓":"Concluir"}</button>`:""}`;r.appendChild(e)});r.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>toggle(S.taskCompletions,b.dataset.t,dk(selectedDate)))}
function renderStats(){let h=todayHabits(),p=todayPrayers(),t=todayTasks(),hc=h.filter(x=>done(S.habitCompletions,x.id)).length,pc=p.filter(x=>done(S.prayerCompletions,x.id)).length,tc=t.filter(x=>done(S.taskCompletions,x.id)).length,total=h.length+p.length+t.length,n=hc+pc+tc,pct=total?Math.round(n/total*100):0;habitSummary.textContent=`${hc} de ${h.length}`;prayerSummary.textContent=`${pc} de ${p.length}`;taskSummary.textContent=`${t.length-tc} pendentes`;statHabits.textContent=`${hc}/${h.length}`;statPrayers.textContent=`${pc}/${p.length}`;statTasks.textContent=`${tc}/${t.length}`;overallPercent.textContent=`${pct}%`;overallBar.style.width=`${pct}%`;let q=[...h.filter(x=>!done(S.habitCompletions,x.id)).map(x=>`Hábito: ${x.name}`),...p.filter(x=>!done(S.prayerCompletions,x.id)).map(x=>`Oração: ${x.name}`),...t.filter(x=>!done(S.taskCompletions,x.id)).map(x=>`Tarefa: ${x.name}`)];pendingList.innerHTML=q.length?q.slice(0,8).map(x=>`<li>${esc(x)}</li>`).join(""):"<li>Nenhuma pendência 🎉</li>"}
function itemsForDate(date){let items=[];S.routine.filter(r=>routineOn(r,date)).forEach(r=>items.push({time:r.start||"",name:r.name,type:"routine",meta:r.category||"Rotina"}));S.habits.filter(h=>sched(h,date)&&h.time).forEach(h=>items.push({time:h.time,name:h.name,type:"habit",meta:"Hábito"}));S.prayers.filter(p=>sched(p,date)&&p.time).forEach(p=>items.push({time:p.time,name:p.name,type:"prayer",meta:"Oração"}));S.tasks.filter(t=>sched(t,date)&&t.time).forEach(t=>items.push({time:t.time,name:t.name,type:"task",meta:"Tarefa"}));return items.sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99"))}
function timelineHTML(items){return items.length?items.map(i=>`<div class="timeline-row"><div class="timeline-time">${i.time||"—"}</div><div class="timeline-card ${i.type}"><strong>${esc(i.name)}</strong><small>${esc(i.meta)}</small></div></div>`).join(""):'<p class="empty">Nenhuma atividade prevista.</p>'}
function renderHomeRoutine(){homeRoutineList.innerHTML=timelineHTML(S.routine.filter(r=>routineOn(r,new Date())).map(r=>({time:r.start||"",name:r.name,type:"routine",meta:r.category||"Rotina"})).sort((a,b)=>a.time.localeCompare(b.time)))}
function renderDay(){selectedDayTitle.textContent=fdate(selectedDate);dayTimeline.innerHTML=timelineHTML(itemsForDate(selectedDate));renderTasks()}
function weekStart(d){let x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-x.getDay());return x}
function renderWeek(){let start=weekStart(selectedDate),days=[];for(let i=0;i<7;i++){let d=new Date(start);d.setDate(start.getDate()+i);days.push(d)}weekStrip.innerHTML=days.map(d=>`<button class="week-day ${dk(d)===dk(selectedDate)?"active":""}" data-weekdate="${dk(d)}"><span>${["DOM","SEG","TER","QUA","QUI","SEX","SÁB"][d.getDay()]}</span><strong>${d.getDate()}</strong></button>`).join("");weekStrip.querySelectorAll("[data-weekdate]").forEach(b=>b.onclick=()=>{selectedDate=pd(b.dataset.weekdate);renderWeek();renderDay()});let all=[];days.forEach(d=>itemsForDate(d).forEach(i=>all.push({...i,date:d})));weekTimeline.innerHTML=all.length?all.map(i=>`<div class="timeline-row"><div class="timeline-time">${String(i.date.getDate()).padStart(2,"0")}/${String(i.date.getMonth()+1).padStart(2,"0")}<br>${i.time||"—"}</div><div class="timeline-card ${i.type}"><strong>${esc(i.name)}</strong><small>${esc(i.meta)}</small></div></div>`).join(""):'<p class="empty">Nada previsto nesta semana.</p>'}
function renderMonth(){let y=calendarDate.getFullYear(),m=calendarDate.getMonth();calendarTitle.textContent=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(calendarDate);let first=new Date(y,m,1,12),start=new Date(first);start.setDate(1-first.getDay());let html="";for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let hasT=tasksFor(d).length>0,hasP=S.prayers.some(p=>sched(p,d)),hasR=S.routine.some(r=>routineOn(r,d));html+=`<button class="calendar-day ${d.getMonth()!==m?"other":""} ${dk(d)===dk(new Date())?"today":""} ${dk(d)===dk(selectedDate)?"selected":""}" data-caldate="${dk(d)}">${d.getDate()}<span class="calendar-dots">${hasT?'<i class="dot"></i>':''}${hasP?'<i class="dot prayer"></i>':''}${hasR?'<i class="dot routine"></i>':''}</span></button>`}calendarGrid.innerHTML=html;calendarGrid.querySelectorAll("[data-caldate]").forEach(b=>b.onclick=()=>{selectedDate=pd(b.dataset.caldate);calendarDate=new Date(selectedDate);renderMonth();renderDay();monthSelectedTitle.textContent=fdate(selectedDate);monthDayList.innerHTML=timelineHTML(itemsForDate(selectedDate))});monthSelectedTitle.textContent=fdate(selectedDate);monthDayList.innerHTML=timelineHTML(itemsForDate(selectedDate))}
function renderRoutine(){let a=routineFilter==="today"?S.routine.filter(r=>routineOn(r,new Date())):S.routine.filter(r=>!r.archived);routineList.innerHTML=a.length?a.sort((x,y)=>(x.start||"").localeCompare(y.start||"")).map(r=>`<div class="list-item"><div class="list-main"><strong>${esc(r.name)}</strong><small>${esc(r.category)} • ${r.start||"—"}${r.end?`–${r.end}`:""} • ${weekdayNames(r.weekdays)}</small></div><button class="status" data-routine-edit="${r.id}">Editar</button></div>`).join(""):'<p class="empty">Nenhum item de rotina.</p>';routineList.querySelectorAll("[data-routine-edit]").forEach(b=>b.onclick=()=>openRoutineForm(S.routine.find(r=>r.id===b.dataset.routineEdit)))}
function weekdayNames(arr=[]){let n=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];return arr.map(x=>n[x]).join(", ")}
function renderAll(){renderHabits();renderPrayers();renderStats();renderHomeRoutine();renderDay();renderWeek();renderMonth();renderRoutine()}

document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>go(b.dataset.target));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));function go(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.target===id));scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-agenda-mode]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-agenda-mode]").forEach(x=>x.classList.toggle("active",x===b));["Day","Week","Month","Routine"].forEach(x=>document.getElementById("agenda"+x+"View").classList.add("hidden"));document.getElementById("agenda"+b.dataset.agendaMode[0].toUpperCase()+b.dataset.agendaMode.slice(1)+"View").classList.remove("hidden")})
document.querySelectorAll("[data-habit-view]").forEach(b=>b.onclick=()=>{habitView=b.dataset.habitView;document.querySelectorAll("[data-habit-view]").forEach(x=>x.classList.toggle("active",x===b));renderHabits()});document.querySelectorAll("[data-prayer-view]").forEach(b=>b.onclick=()=>{prayerView=b.dataset.prayerView;document.querySelectorAll("[data-prayer-view]").forEach(x=>x.classList.toggle("active",x===b));renderPrayers()});
document.querySelectorAll("[data-routine-filter]").forEach(b=>b.onclick=()=>{routineFilter=b.dataset.routineFilter;document.querySelectorAll("[data-routine-filter]").forEach(x=>x.classList.toggle("active",x===b));renderRoutine()})
prevMonth.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderMonth()};nextMonth.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderMonth()};

createBtn.onclick=()=>createDialog.showModal();document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{if(createDialog.open)createDialog.close();if(b.dataset.action==="habit")openHabitForm();else if(b.dataset.action==="prayer")openPrayerForm();else openTaskForm()});createRoutineBtn.onclick=()=>{createDialog.close();openRoutineForm()};addRoutineBtn.onclick=()=>openRoutineForm();

function freqUI(prefix){let t=document.getElementById(prefix+"Frequency").value,map={weekly:"Weekly",monthly:"Monthly",yearly:"Yearly",date:"DateBox",range:"Range"};["Weekly","Monthly","Yearly","DateBox","Range"].forEach(x=>document.getElementById(prefix+x).classList.add("hidden"));if(map[t])document.getElementById(prefix+map[t]).classList.remove("hidden")}
habitFrequency.onchange=()=>freqUI("habit");prayerFrequency.onchange=()=>freqUI("prayer");taskFrequency.onchange=()=>freqUI("task");
function readFreq(prefix){let t=document.getElementById(prefix+"Frequency").value,f={type:t};if(t==="weekly"){f.weekdays=[...document.querySelectorAll(`#${prefix}Weekly input:checked`)].map(x=>Number(x.value));if(!f.weekdays.length)throw"Escolha pelo menos um dia."}if(t==="monthly")f.day=Number(document.getElementById(prefix+"MonthDay").value);if(t==="yearly")f.date=document.getElementById(prefix+"YearDate").value;if(t==="date")f.date=document.getElementById(prefix+"Date").value;if(t==="range"){f.start=document.getElementById(prefix+"StartDate").value;f.end=document.getElementById(prefix+"EndDate").value;if(!f.start||!f.end||f.end<f.start)throw"Confira o intervalo."}if((t==="yearly"||t==="date")&&!f.date)throw"Escolha a data.";return f}
function fillFreq(prefix,f={type:"daily"}){document.getElementById(prefix+"Frequency").value=f.type||"daily";document.querySelectorAll(`#${prefix}Weekly input`).forEach(c=>c.checked=(f.weekdays||[]).includes(Number(c.value)));document.getElementById(prefix+"MonthDay").value=f.day||1;document.getElementById(prefix+"YearDate").value=f.date||"";document.getElementById(prefix+"Date").value=f.date||"";document.getElementById(prefix+"StartDate").value=f.start||"";document.getElementById(prefix+"EndDate").value=f.end||"";freqUI(prefix)}

function openRoutineForm(r=null){routineFormTitle.textContent=r?"Editar item da rotina":"Novo item da rotina";routineId.value=r?.id||"";routineName.value=r?.name||"";routineStart.value=r?.start||"";routineEnd.value=r?.end||"";routineCategory.value=r?.category||"Pessoal";document.querySelectorAll("#routineWeekdays input").forEach(c=>c.checked=(r?.weekdays||[]).includes(Number(c.value)));routineHabitLink.innerHTML='<option value="">Nenhum</option>'+S.habits.filter(h=>!h.archived).map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join("");routineHabitLink.value=r?.habitId||"";routineDialog.showModal()}
cancelRoutine.onclick=()=>routineDialog.close();routineForm.onsubmit=e=>{e.preventDefault();let days=[...document.querySelectorAll("#routineWeekdays input:checked")].map(x=>Number(x.value));if(!days.length){alert("Escolha pelo menos um dia.");return}let id=routineId.value,old=id?S.routine.find(r=>r.id===id):null,o={id:id||crypto.randomUUID(),name:routineName.value.trim(),start:routineStart.value,end:routineEnd.value,category:routineCategory.value,weekdays:days,habitId:routineHabitLink.value||"",archived:false};if(id)S.routine[S.routine.findIndex(r=>r.id===id)]={...old,...o};else S.routine.push(o);save();routineDialog.close()}

function openHabitForm(h=null){habitFormTitle.textContent=h?"Editar hábito":"Novo hábito";habitId.value=h?.id||"";habitName.value=h?.name||"";habitCategory.value=h?.category||"Espiritual";habitTime.value=h?.time||"";fillFreq("habit",h?.frequency||{type:"daily"});selectEmoji(h?.icon||"📖");habitDialog.showModal()}
cancelHabit.onclick=()=>habitDialog.close();habitForm.onsubmit=e=>{e.preventDefault();try{let id=habitId.value,old=id?S.habits.find(x=>x.id===id):null,o={id:id||crypto.randomUUID(),name:habitName.value.trim(),icon:habitIcon.value,category:habitCategory.value,time:habitTime.value,frequency:readFreq("habit"),archived:old?.archived||false};if(id)S.habits[S.habits.findIndex(x=>x.id===id)]={...old,...o};else S.habits.push(o);save();habitDialog.close()}catch(m){alert(m)}}
function selectEmoji(e){habitIcon.value=e;habitIconPreview.textContent=e;emojiPicker.querySelectorAll(".emoji-option").forEach(b=>b.classList.toggle("selected",b.dataset.emoji===e))}
boldBtn.onclick=()=>{prayerEditor.focus();document.execCommand("bold",false,null)};separatorBtn.onclick=()=>{prayerEditor.focus();document.execCommand("insertHTML",false,"<hr><br>")};
function openPrayerForm(p=null){prayerFormTitle.textContent=p?"Editar oração":"Nova oração";prayerId.value=p?.id||"";prayerName.value=p?.name||"";prayerEditor.innerHTML=p?.html||((p?.text||"").replace(/\n/g,"<br>"));prayerTime.value=p?.time||"";fillFreq("prayer",p?.frequency||{type:"daily"});prayerFormDialog.showModal()}
cancelPrayerForm.onclick=()=>prayerFormDialog.close();prayerForm.onsubmit=e=>{e.preventDefault();try{let id=prayerId.value,old=id?S.prayers.find(x=>x.id===id):null,o={id:id||crypto.randomUUID(),name:prayerName.value.trim(),html:prayerEditor.innerHTML,text:prayerEditor.innerText,time:prayerTime.value,frequency:readFreq("prayer"),archived:old?.archived||false};if(id)S.prayers[S.prayers.findIndex(x=>x.id===id)]={...old,...o};else S.prayers.push(o);save();prayerFormDialog.close()}catch(m){alert(m)}}
function openTaskForm(t=null){taskFormTitle.textContent=t?"Editar tarefa":"Nova tarefa";taskId.value=t?.id||"";taskName.value=t?.name||"";taskNotes.value=t?.notes||"";taskCategory.value=t?.category||"Pessoal";taskPriority.value=t?.priority||"normal";taskTime.value=t?.time||"";fillFreq("task",t?.frequency||{type:"date",date:dk(selectedDate)});taskFormDialog.showModal()}
cancelTaskForm.onclick=()=>taskFormDialog.close();taskForm.onsubmit=e=>{e.preventDefault();try{let id=taskId.value,old=id?S.tasks.find(x=>x.id===id):null,o={id:id||crypto.randomUUID(),name:taskName.value.trim(),notes:taskNotes.value.trim(),category:taskCategory.value,priority:taskPriority.value,time:taskTime.value,frequency:readFreq("task"),archived:old?.archived||false};if(id)S.tasks[S.tasks.findIndex(x=>x.id===id)]={...old,...o};else S.tasks.push(o);save();taskFormDialog.close()}catch(m){alert(m)}}
function openHabit(id){activeHabit=id;let h=S.habits.find(x=>x.id===id);habitDetailIcon.textContent=h.icon||"⭐";habitDetailName.textContent=h.name;habitDetailMeta.textContent=[h.category,flabel(h),h.time].filter(Boolean).join(" • ");habitDetailDialog.showModal()}editHabit.onclick=()=>{let h=S.habits.find(x=>x.id===activeHabit);habitDetailDialog.close();setTimeout(()=>openHabitForm(h),80)};archiveHabit.onclick=()=>{let h=S.habits.find(x=>x.id===activeHabit);if(confirm(`Arquivar "${h.name}"?`)){h.archived=true;save();habitDetailDialog.close()}};closeHabitDetail.onclick=()=>habitDetailDialog.close();
function openPrayer(id){activePrayer=id;let p=S.prayers.find(x=>x.id===id);prayerTitle.textContent=p.name;prayerMeta.textContent=[flabel(p),p.time].filter(Boolean).join(" • ");prayerText.innerHTML=p.html||esc(p.text||"Sem texto cadastrado.").replace(/\n/g,"<br>");finishPrayer.textContent=done(S.prayerCompletions,id)?"Desmarcar finalização":"Marcar como finalizada";prayerDetailDialog.showModal()}finishPrayer.onclick=()=>{toggle(S.prayerCompletions,activePrayer);prayerDetailDialog.close()};editPrayer.onclick=()=>{let p=S.prayers.find(x=>x.id===activePrayer);prayerDetailDialog.close();setTimeout(()=>openPrayerForm(p),80)};archivePrayer.onclick=()=>{let p=S.prayers.find(x=>x.id===activePrayer);if(confirm(`Arquivar "${p.name}"?`)){p.archived=true;save();prayerDetailDialog.close()}};closePrayer.onclick=()=>prayerDetailDialog.close();
habitHistoryBtn.onclick=()=>showHistory("habit");prayerHistoryBtn.onclick=()=>showHistory("prayer");function showHistory(type){let map=type==="habit"?S.habitCompletions:S.prayerCompletions,items=type==="habit"?S.habits:S.prayers,rows=[];for(let k in map){let[i,date]=k.split("|"),it=items.find(x=>x.id===i);if(it)rows.push({date,name:it.name})}rows.sort((a,b)=>b.date.localeCompare(a.date));historyTitle.textContent=type==="habit"?"Histórico de hábitos":"Histórico de orações";historyContent.innerHTML=rows.length?rows.map(r=>`<div class="history-row done"><span>${esc(r.name)}</span><strong>${short(r.date)}</strong></div>`).join(""):'<p class="empty">Ainda não há registros.</p>';historyDialog.showModal()}closeHistory.onclick=()=>historyDialog.close();
function showArchived(type){let a=(type==="habit"?S.habits:S.prayers).filter(x=>x.archived);archiveTitle.textContent=type==="habit"?"Hábitos arquivados":"Orações arquivadas";archiveContent.innerHTML=a.length?a.map(x=>`<div class="list-item"><div class="list-main"><strong>${esc(x.name)}</strong></div><div class="archive-actions"><button data-restore="${x.id}" data-type="${type}">Restaurar</button></div></div>`).join(""):'<p class="empty">Nenhum item arquivado.</p>';archiveContent.querySelectorAll("[data-restore]").forEach(b=>b.onclick=()=>{let arr=b.dataset.type==="habit"?S.habits:S.prayers,item=arr.find(x=>x.id===b.dataset.restore);item.archived=false;save();showArchived(b.dataset.type)});archiveDialog.showModal()}habitArchivedBtn.onclick=()=>showArchived("habit");prayerArchivedBtn.onclick=()=>showArchived("prayer");closeArchive.onclick=()=>archiveDialog.close();

if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
renderAll();